### ISSUE TITLE
Move leaderboard data over to website API

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#100]
Move leaderboard data over to website API and then have the website pull that data from the API rather than the static data from the repo.

**Comment by ma2b0043** [comment]
@angle943 @ThaDeveloper whats the status of this issue ?

**Comment by angle943** [comment]
@ma2b0043 I would say that this is currently blocked, due to us needing to figure out how to authenticate a user's account # and github account properly. @buckyroberts , @kristykjlee , and I had a couple talks regarding this issue, but I don't believe the talks were finalized.

To give you a certain background, the issue is this. Try checking our current page: https://thenewboston.com/leaderboard/All (and also, to see some results, click on `All` filer on the top right)

The contributors that you see here is manually entered here: https://github.com/thenewboston-developers/Website/blob/development/src/data/contributors.json

The tasks you see are manually entered here: https://github.com/thenewboston-developers/Website/blob/development/src/data/tasks.json

As you can tell, manually adding these tasks here is very cumbersome, and not a long term solution, so we hope to use our newly integrated `website-api` to handle the user data, rather than manually entering it.

The problem right now is, a user can currently add any account# he/she wants in the profile, and he/she can also add any github username in their profile. Thus they can pretend to be someone else.

We obviously want to prevent that from happening, and although we came up with a couple good solutions, I don't believe we have finalized our talks.

@ma2b0043 we will keep you posted if we figure out how we are going to do this

**Comment by ma2b0043** [comment]
Got it. Thank you for the update :+1: .
