### ISSUE TITLE
Look into slow query

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#210]
Look into slow queries for the video page on the website https://thenewboston.com/tutorials/All

**Comment by jamessspanggg** [comment]
The slow queries are due to the extra fetches for the instructors of each playlist, which I added previously as I realise that those data were missing. Could we nest the basic information about the instructor in the playlist itself? i.e. `instructor name`, and `instructor channel url`.

<img width="388" alt="Screen Shot 2021-05-26 at 8 12 04 PM" src="https://user-images.githubusercontent.com/32864116/119657712-d5e9ba80-be5e-11eb-8079-de6a54d25ba2.png">

**Comment by manishram** [comment]
Hey @jamessspanggg also size of images is bigger than the rendering size. For example https://i.imgur.com/uZ5M8Pp.png

**Comment by jamessspanggg** [comment]
> Hey @jamessspanggg also size of images is bigger than the rendering size. For example https://i.imgur.com/uZ5M8Pp.png

nice catch, btw, we can resize the `imgur` images by appending the resolution size at the end. [Reference](https://superuser.com/questions/1238552/how-to-resize-quickly-a-imgur-image)

For example with the image u provided, we can append `m` to have a medium size, i.e. `https://i.imgur.com/uZ5M8Ppm.png`

**Comment by buckyroberts** [comment]
@jamessspanggg updated the response on the website API and also the frontend to handle the new nested data https://github.com/thenewboston-developers/Website/pull/1820/files - the page is noticeably faster already.

@manishram @jamessspanggg I am having new thumbnails created. I will make sure that they are the proper size. Thanks for the heads up!
