### ISSUE TITLE
Terms of Service & Privacy Policy for website

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#39]
Needed before users can upload data (especially to the marketplace)

**Comment by shaheerwasti** [comment]
I want to help in the creation and development of this card. @buckyroberts any kind suggestions or reference links, reading to kick me in a right direction?

**Comment by buckyroberts** [comment]
Unfortunately not @shaheerwasti - I have zero legal background. I only know that we should have Terms of Service & Privacy Policy before handling user data.

**Comment by manishram** [comment]
Hey, @buckyroberts I am sure but can we use generators for this?
For example: https://termify.io/

**Comment by manishram** [comment]
**Terms of Service**: https://docs.google.com/document/d/1ZFljmSXBXmLPqRMuRYuiT2petHmZJIVRWpwC2UvOXqM/edit?usp=sharing

**Privacy Policy**: https://docs.google.com/document/d/1A60HvMrI86DidHTwzBkN5zNUrtZKorAqMiPCHAMSgXI/edit?usp=sharing

Using https://termify.io/ 

**PS**: This is just for demo purposes. Some information needs to be updated because I'm not aware of them. For example: if the site uses Facebook Pixel or not.

**Comment by shaheerwasti** [comment]
[reference](https://thenewboston.slack.com/archives/C07PJ5ETS/p1607433115344200) for any leads
