### ISSUE TITLE
Create system to handle GitHub issues

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#59]
There are a growing number of issues and PR's in several repos, most noticeably the Account Manager repo:

- https://github.com/thenewboston-developers/Account-Manager/issues
- https://github.com/thenewboston-developers/Account-Manager/pulls

There are a few reasons for this that we need to address and fix.

1. Lot's of bug reports, issues, suggestions, etc... are coming in with no clear system around how we are filtering/handling those.
2. New users are working on issues, suggestions, etc... before anyone on the team has had a chance to review it.Some of these suggestions end up not being needed. This results in a lot of wasted time and PR's.
3. Because of these PR's that are submitted where the underlying issue was never reviewed by the team, the engineering team leads are unclear what they should do with those PR's.

**Comment by shaheerwasti** [comment]
The issue is we have people creating issues (it’s funny if you read it this way :p) and we can’t stop them from doing so. @Spotnag and I have taken a quick look at Github actions to see if we could create some automation around it. There are ways to create CI, CD pipelines but there was nothing which could automatically set the cards for review to team leads before someone could make a PR for a new issue. So, we agreed on creating following labels,

**1. To be Reviewed - Do not make a PR
2. Under Review - Do not make a PR
3. Ready for PR**

Team Leads of their respective repos are going to be responsible for setting the labels of new issues accordingly.

**Comment by Spotnag** [comment]
The above should be fine for now, although we should look to take lessons from big open source projects on github that have  been live for some time. e.g. flutter, 5k+ issues with 150 pull reqeusts. I will look into they and other projects currently handle this. Taking a step back it looks like the issues and pull requests are not the problem but rather the fact that we may want to reward an amount to the pull request.

As it is open source this might not be an issue and maybe we dont add them retrospectively, if people would like to help the project in anyway they can they should. Rewards can be added to issues reviewed by the dev team if noone picks them up as an incentive.
