### ISSUE TITLE
Node Incentive Program

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#60]
https://docs.google.com/document/d/1_1b9YbIyXtMnjB0VCokVs1Xz4j8t_DBIe8ajxR4Arlg/edit?usp=sharing

**TBD**
- How to track/verify active nodes (reliability as well)
- Process for Payment Team sending payments

**Notes / Thoughts**
- Should we continuously fund nodes? They are indeed continuously helping the network.
- By continuously funding nodes we are locking in an impactful long term decision very early on in the network. This is especially tricky since these nodes are already incentivized through other means.
- Possibly best to run this program for a limited time (and limited cap) to test and take note of any issues before expanding by increasing the cap or amount of time to run the program.

**Comment by TheBrokenWasp** [comment]
Just a question, what about nodes that have been up for a while even before the program initiated? My CV has been up for since the 29th of November and has already been hired by 2 banks including the default bank. It has been up nonstop and I am pretty sure it has been reliable as well. Would any of this be counted toward the requirements, and if so, which ones? If not then that is fine, I am not planning on taking it down anytime ever, I'm just curious
