### ISSUE TITLE
Completion of thenewboston-js

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Management#62]
- Find out the status of https://github.com/thenewboston-developers/thenewboston-js from @sno2 or @mrbusysky
- Note any additional work that needs complete before it's ready for developers (additional functions, documentation, examples, etc...)
- Write up tickets
- Find a new lead for `thenewboston-js` (@sno2 asked to work on the backend porting our servers to Rust)

**Comment by shaheerwasti** [comment]
Left the message to @sno2 on slack. 
I am unable to identify @mrbusysky on slack. Please mention his slack name.

**Comment by sno2** [comment]
@buckyroberts Ok, I will start organizing/creating the tasks.  I was trying to work on how a payment handler would work and will post an issue for discussion on what I was thinking about in the repo.  We do still need documentation, however all of the JSDoc for methods, classes, and some class properties.  I do have a question, however; are we going to put the documentation on website.  I would prefer we do it in markdown as markdown is easy to use for virtually all developers.  Thanks

**Comment by shaheerwasti** [comment]
I had the chance to chat with Skyler and Carter, and they were so kind to explain me different stuff about this chain. With their help, I was able to assert that at this point we need to prioritize the documentation of `thenewboston-js` in addition to `json RPC post` methods. This way we can facilitate anyone who wants to build applications using this library. 

Carter, since he did write probably > 95% of the code base so, he is going to jolt this crucial document down. I agree with him that this should be in markdown. Also, he will work on creating the request method too. but! carter has his exams lined up so he is also preparing for them and this might result in some delays. He told me that he’ll update us on this.

**Comment by zinoadidi** [comment]
Hi guys, @buckyroberts @shaheerwasti I would like to take over the lead from carter, I have good experience leading multiple JS/TS teams as well as published lots of private packages for various clients.

I can organize development and get things going; organize the team or make some noise for new members and set up a roadmap / manage and create necessary tasks to keep development going on here.

My Linkedin >> https://www.linkedin.com/in/zinoadidi/
